### PR TITLE
optimized mascot.svg

### PR DESCRIPTION
**Pull request by RiedleroD**
List of what I changed:

- formatting for readability
- replaced width/height with viewBox
- fixed incorrect usage of id
- unified stroke width
- resolved transforms
- cleaned up some messy paths
- regrouped to remove style tag
- combined paths with the same style

this means rendering of the SVG is now more efficient and the size of the file itself is smaller. One small issue: broken SVG renderers like old versions of rsvg or QtSVG might not be able to accurately render the image. Modern Browsers use neither, so this is only relevant if the logo is used in some Qt application or on wikipedia (wikimedia uses an old version of rsvg which still has the short-arc-flags bug)

### CODE REVIEW

**Comment by RiedleroD** [comment]
I've also made a variant for when it's displayed as a very small icon, which is what I'm going to use on my website (with your permission) to link to my userstyles.world account. I can open a separate PR or add it to this one if you want to add it to the official resources.

small variant

**Review by vednoc — CHANGES_REQUESTED** [review]
Looks good to me. The only problem is, you should've used `dev` branch since we've changed `static/mascot.svg` to `web/static/mascot.svg` in the recent commits. Could you do a rebase or would you like me [to try] to handle it for you?

**Comment by vednoc** [comment]
> I've also made a variant for when it's displayed as a very small icon, which is what I'm going to use on my website (with your permission) to link to my userstyles.world account. I can open a separate PR or add it to this one if you want to add it to the official resources.

CC @Gusted. 😄

**Review by Gusted — APPROVED** [review]

**Comment by Gusted** [comment]
as for the SVG's code LGTM.

**Comment by Gusted** [comment]
> CC @Gusted. smile

Fine by me if it's suffixed with the appropriate size ex. `_16x16.png`

**Comment by RiedleroD** [comment]
I think the rebase worked.

Regarding the variant, I don't think a suffix with pixel size is appropriate, since 16x16 on my 1440p screen is vastly different from the same on a 720p screen. Maybe the suffix `_small.svg` would be better?

**Review by vednoc — APPROVED** [review]
Looks good! I'll wait for the other SVG until and then merge this PR.

**Comment by Gusted** [comment]
> Regarding the variant, I don't think a suffix with pixel size is appropriate, since 16x16 on my 1440p screen is vastly different from the same on a 720p screen. Maybe the suffix `_small.svg` would be better?

It should have a suffix indicating the viewport size. But given this is a SVG it can be a bit more loosely so `_small.svg` should be good.

**Review by vednoc — APPROVED** [review]
LGTM. Thank you for contributing! 🎉

**Pull request merged**
