### PR TITLE
Delete Dark-Spotify Userstyle

### PR DESCRIPTION
**Pull request by AbhayAysola**
I decided to delete the spotify theme that I made since I wasn't maintaining it.

### CODE REVIEW

**Comment by vednoc** [comment]
Back when I decided to replace Hugo, almost everything except Sass files ended up being removed. I apologize for the confusion since commits haven't been pushed yet, but I appreciate taking the time to make this PR. Rewrite should go live for the first public test later today, I'm just waiting on a couple of things.

P.S. Fun fact: Hugo failed to build USw for the last couple of months because your repository could no longer be fetched. 😄

**Comment by AbhayAysola** [comment]
> Back when I decided to replace Hugo, almost everything except Sass files ended up being removed. I apologize for the confusion since commits haven't been pushed yet, but I appreciate taking the time to make this PR. Rewrite should go live for the first public test later today, I'm just waiting on a couple of things.
> 
> P.S. Fun fact: Hugo failed to build USw for the last couple of months because your repository could no longer be fetched. 😄

Wow! I'm really excited to see what you've got going on. Looks like this project is up and running again :)

Also I'm really sorry about the Hugo failing thing, I should have thought a bit more before deleting that repo 😅

**Comment by vednoc** [comment]
I chose to rewrite it in Go, and I honestly had the best time researching and learning new things while building it. A good amount of code from templates was reused, so the layout hasn't changed much! You could try out a [public-ish test][1] running code from a couple of weeks ago. That version is missing import functionality, as well as quite a few other things.

> Also I'm really sorry about the Hugo failing thing

It's all good. If I wasn't working on a rewrite, I would've fixed it pretty quickly. Not sure if Hugo has a way around it, but from my small research I couldn't find anything. Alas, it's no longer something to be worried about. 😄 

[1]: https://www.v1.userstyles.world/

**Comment by AbhayAysola** [comment]
Cool, I've been looking to learn Go for the past few months and never really got around to doing it. This is the perfect push for me to do that. Really excited to see how this works. After taking a small look at that test, I see that the styles are being stored on the website itself, pretty cool stuff!

**Comment by vednoc** [comment]
Do it! It's a _very_ simple language. [LearnXinYminutes][1] will teach you most of the language. There is also [Tour of Go][2] that is also quite good. There are more resources out there, but these two should get you familiar with Go in a few hours. Feel free to reach out if you get stuck, I'm always down to help.

[1]: https://learnxinyminutes.com/docs/go/
[2]: https://tour.golang.org/list

**Comment by AbhayAysola** [comment]
> Do it! It's a _very_ simple language. [LearnXinYminutes](https://learnxinyminutes.com/docs/go/) will teach you most of the language. There is also [Tour of Go](https://tour.golang.org/list) that is also quite good. There are more resources out there, but these two should get you familiar with Go in a few hours. Feel free to reach out if you get stuck, I'm always down to help.

Thanks a ton! I'll definitely check those out. I started the Tour of Go thing but I never really finished it. Seems like a pretty simple and straightforward language though. Thanks for offering to help :D

**Pull request closed without merging**
